# **NumPy**

In [1]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [2]:
bmi > 23

array([False, False, False,  True, False])

In [3]:
bmi[bmi > 23]

array([24.7473475])

* `logical_and()`
* `logical_or()`
* `logical_not()`

In [9]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

In [8]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

In [5]:
np.logical_or(bmi > 21, bmi < 21)

array([ True,  True,  True,  True,  True])

In [6]:
np.logical_not(bmi > 21, bmi < 21)

array([False,  True, False, False, False])

## **For Loop in NumPy Arrays**

**1D NumPy Arrays**

In [10]:
for val in bmi:
    print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


**2D NumPy Arrays**

if we want to print out each element in this 2D array separately, the same basic for loop won't do the trick though. The 2D array is actually built up from an array of 1D arrays. The for loop simply prints out an entire array on each iteration.

In [11]:
meas = np.array([np_height, np_weight])
for val in meas:
    print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


To get every element of an array, you can use a NumPy function called `nditer()`.

In [12]:
for val in np.nditer(meas):
    print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


This time, we get 10 printouts, **first all the heights, then all the weights.**

## **Coin toss**
Exercise

In [1]:
import numpy as np
np.random.seed(123)
coin = np.random.randint(0, 2) # Randomly generate 0 or 1
print(coin)

if coin == 0:
    print("heads")
else:
    print("tails")

0
heads


In [4]:
import numpy as np
np.random.seed(123)

step = 50

dice = np.random.randint(1, 7) # Randomly generate 0 or 1

if dice <= 2:
    step -= 1
elif dice <= 5:
    step += 1
else:
    step += np.random.randint(1, 7)

print(dice)
print(step)

6
53
